name: ' be-in'
favicon: null
layout_spectrum: 0.07164201303385198
typography_spectrum: 0.8900100167375058
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.708700398914516
  lightness: 0.005920775001868606
  saturation: 0.9399744833353907
  rhythmicContrast: 0.6954069316852838
purpose: []
